fix: Crash when getting instance of TelegramBot
org.koin.core.error.NoBeanDefFoundException: No definition found for type 'eu.vendeli.tgbot.TelegramBot'. Check your Modules configuration and add missing type and/or qualifier!
	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:302)